version: '3'

services:
  todolistmysql:
    image: mysql:latest
    container_name: todolistmysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '9001:3306'
    volumes:
      - ./database:/var/lib/mysql
