version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: todo_task
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '9001:3306'
    volumes:
      - ./mysql:/var/lib/mysql
